<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Backoffice_dropdown-item</name>
   <tag></tag>
   <elementGuidId>2d7d31f6-eafd-4d15-a32f-4c0071df8660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='company']/div/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d47c2b8-819c-402b-940b-4b93f42983d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>11f846a1-fcd5-40f4-8584-732b1a419e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/es/Company/Index</value>
      <webElementGuid>9b8d25a1-5ff2-4571-b544-344dac4df9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                     Configuración
                                </value>
      <webElementGuid>69babeab-2c45-4413-b41d-1240a53a560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)/div[@class=&quot;collapse navbar-collapse ms-auto&quot;]/div[@class=&quot;nav-item dropdown&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-end&quot;]/li[1]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>80e74e00-1ed1-45fd-a9cc-a98718e874ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='company']/div/div[2]/ul/li/a</value>
      <webElementGuid>20039f59-ad09-40fd-897f-e976fd460eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Configuración']/parent::*</value>
      <webElementGuid>b52a947b-1f75-495c-9917-77a73f239cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/es/Company/Index')]</value>
      <webElementGuid>0be1a85f-5d8b-40fa-b87a-187509e651f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>e75e4c9b-198f-4c0d-96a6-940d6e8230b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/es/Company/Index' and (text() = '
                                     Configuración
                                ' or . = '
                                     Configuración
                                ')]</value>
      <webElementGuid>ed1c4868-3106-4426-97cf-75fb96e0b8c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
