<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Empresa_text-decoration-none</name>
   <tag></tag>
   <elementGuidId>a80fd7e6-85bb-41ae-825a-66fd495ec4c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.text-decoration-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-layout-container']/div/div/div/div/nav/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>abfb5624-660f-4c09-9b06-67a15a37d996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-decoration-none</value>
      <webElementGuid>6e9d7074-41c6-460c-8cd8-11c25876353a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/es/Company/Fields</value>
      <webElementGuid>17bde709-bf52-4240-b57a-8361952ccd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campos</value>
      <webElementGuid>744c5393-4aa3-4126-9713-fd03441846ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout-container&quot;)/div[@class=&quot;main-panel&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 nav-sidebar&quot;]/nav[1]/ul[@class=&quot;list-unstyled&quot;]/li[2]/a[@class=&quot;text-decoration-none&quot;]</value>
      <webElementGuid>d9d005cc-64be-465f-a373-e67c31a4659e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-layout-container']/div/div/div/div/nav/ul/li[2]/a</value>
      <webElementGuid>6bdf3c39-514b-457f-83b8-429057f9bb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Campos')]</value>
      <webElementGuid>5392f78a-0eba-4dbe-ae98-3a4da425972a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empresa'])[1]/following::a[1]</value>
      <webElementGuid>9c080b7f-42f3-47cb-919f-21e2526a1ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración'])[1]/following::a[2]</value>
      <webElementGuid>9abb02a8-2514-4aed-972f-8f54dbd783b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monedas'])[1]/preceding::a[1]</value>
      <webElementGuid>ad072f8b-e97a-430d-ba9b-b44c45e4bda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plantillas'])[1]/preceding::a[2]</value>
      <webElementGuid>07f95a30-46fd-49de-a723-2bc0d2f00edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Campos']/parent::*</value>
      <webElementGuid>a1086b6a-6de4-4946-8681-5ecd49cbaeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/es/Company/Fields')])[2]</value>
      <webElementGuid>a805781c-8b5f-4003-9f25-6ff61ccb1f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/nav/ul/li[2]/a</value>
      <webElementGuid>69e18c25-3cdc-4711-8f1e-d4fadd8ae192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/es/Company/Fields' and (text() = 'Campos' or . = 'Campos')]</value>
      <webElementGuid>9f4f2def-3de5-426e-99aa-1e35faedc027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
