<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Editable por proveedores_Mandatory</name>
   <tag></tag>
   <elementGuidId>e534e1d1-77ab-40f6-8afe-d3e64bce8720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Mandatory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Mandatory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8133e8f-1dbf-4256-87de-4f3b8f48c5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-1 ms-0 check-box</value>
      <webElementGuid>4d8853ba-335a-444e-b855-807d2e308961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7d71825-92c8-4847-a288-42df6a60349a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Mandatory field is required.</value>
      <webElementGuid>775394c9-edda-4156-8a61-464b01c7e47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Mandatory</value>
      <webElementGuid>6696706d-984d-41c7-9f06-49dbe753e24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mandatory</value>
      <webElementGuid>e649ec5b-b142-4012-854f-0801a9de64b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>81da354d-51ed-423b-87ca-5b7e5f464ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96610a46-5fea-49ea-9ee9-a6438f8b83e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Mandatory&quot;)</value>
      <webElementGuid>db8eb5bd-2634-452b-9321-e8af88c66e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Mandatory']</value>
      <webElementGuid>4245293a-c78c-4880-b72f-649ae86368c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-secondary-config-container']/div/div[7]/input</value>
      <webElementGuid>88d7ab07-ec24-4b00-976e-950cf19843d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>c10aaf63-86cc-4f29-8296-11bc94d68db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Mandatory' and @name = 'Mandatory' and @type = 'checkbox']</value>
      <webElementGuid>f4329a0c-a012-43dc-82c9-c69f01226304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
