<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre del campo_auxdata-title</name>
   <tag></tag>
   <elementGuidId>0cf4173e-ead9-493f-a40e-119cf97d83b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auxdata-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auxdata-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e9ccbcb-7bdc-4827-981e-ef402408c748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>9b101fb5-67ad-4ab5-a3a1-ee8b4d38f4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auxdata-title</value>
      <webElementGuid>cbbc66fe-19ec-4afd-a39d-ab0fe5e1dbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>115057c8-047c-4856-ac0c-86cb50d3e139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94410493-cdff-44be-b6c7-d2629eefb4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auxdata-title&quot;)</value>
      <webElementGuid>ec6797b3-31da-435e-9574-fb15dc28ada3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auxdata-title']</value>
      <webElementGuid>92076e9d-d380-4c88-805d-53653b35c047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditSingleFieldForm']/div/div/div/input</value>
      <webElementGuid>b559364a-c361-442f-abb8-a32f40aaa9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>5fd3d43e-8128-480d-8a48-c304d230bb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'auxdata-title' and @name = 'Title' and @type = 'text']</value>
      <webElementGuid>c86d3942-d8f8-410e-896f-a527275e25a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
