<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visible para proveedores_IsEditableSupplier</name>
   <tag></tag>
   <elementGuidId>b227b7d4-05dd-4bd1-9700-db482b8239b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsEditableSupplier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsEditableSupplier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d4af0c2-8803-41d7-89b4-570ec6e6e1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-1 ms-0 check-box</value>
      <webElementGuid>32b971cb-2546-4bdc-95e3-f0770e5c2f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98ad633a-1255-41db-b4c1-8c683c796699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsEditableSupplier field is required.</value>
      <webElementGuid>5e7d4fbf-b584-4097-8b5d-b9e8f261222e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsEditableSupplier</value>
      <webElementGuid>837db252-f1ad-467c-91e3-95abe22db8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsEditableSupplier</value>
      <webElementGuid>e3ae6e11-5874-4699-98a8-fce3dfad24b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>97731f63-522e-4083-bf5d-71eb60d55664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35d17e1a-23e8-451a-885a-3738ac82209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsEditableSupplier&quot;)</value>
      <webElementGuid>60cb614c-78f0-471e-93c4-d08e9d8e18c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsEditableSupplier']</value>
      <webElementGuid>ec90bb1d-4ab1-4554-a13a-96a36458dfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-secondary-config-container']/div/div[6]/div/input</value>
      <webElementGuid>35f69408-c875-439c-91ff-7108e4a80444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>f218b63b-d48f-46d2-b236-39b6bfd931d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsEditableSupplier' and @name = 'IsEditableSupplier' and @type = 'checkbox']</value>
      <webElementGuid>0cf76963-08c2-493c-92a1-d069ab88d8c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
