<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mostrar en tablas_IsVisibleSupplier</name>
   <tag></tag>
   <elementGuidId>8dd35116-1aeb-46d1-b1a3-99e1660709b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsVisibleSupplier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsVisibleSupplier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03866d49-86d8-4120-bec9-21ce08a32e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-1 ms-0 check-box</value>
      <webElementGuid>88612242-930c-4896-90f7-3ba8c304a100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>91285814-12e0-4dfa-880d-b2b971671592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsVisibleSupplier field is required.</value>
      <webElementGuid>400b2343-68f1-4141-9d86-05ab50a162a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsVisibleSupplier</value>
      <webElementGuid>c9f4268a-528f-4052-af2e-acb9e40e302f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsVisibleSupplier</value>
      <webElementGuid>26a28eeb-bde9-48e6-a0c4-32a49c7a474f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9c6c619c-493c-492b-89fd-70dcbd162328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2673838-dc99-46b7-ad93-077229a40ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsVisibleSupplier&quot;)</value>
      <webElementGuid>18cb19c5-0f13-4d1a-a33e-72de8ccb3f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsVisibleSupplier']</value>
      <webElementGuid>d4c5e3df-413d-4be3-ae1d-99c4af06b2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-secondary-config-container']/div/div[5]/div/input</value>
      <webElementGuid>a97f9af3-59e5-485f-a634-be90a674254a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>50200545-b7b0-4fd5-9ca4-0c53d931cb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsVisibleSupplier' and @name = 'IsVisibleSupplier' and @type = 'checkbox']</value>
      <webElementGuid>16f7be03-9ef0-4a65-aa38-df2c017b573b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
