<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Editable por usuarios_IncludeInSearchResult</name>
   <tag></tag>
   <elementGuidId>e59098a8-4a21-4c2d-ab12-dc1b94837263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IncludeInSearchResult</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IncludeInSearchResult']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f85275e7-5949-4cd6-9d9b-54cc7040cab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-1 ms-0 check-box</value>
      <webElementGuid>63f5c2aa-99ed-4ee9-8249-04055d20ca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce9a3650-fec7-47c8-bcc8-ce3d35548d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IncludeInSearchResult field is required.</value>
      <webElementGuid>f250f86d-dad5-4c97-b26b-4f311fde4c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IncludeInSearchResult</value>
      <webElementGuid>03d77f65-1c26-4963-af65-9d2a33589b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IncludeInSearchResult</value>
      <webElementGuid>696d51b4-3a1f-49c4-b42e-5c05484239e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5418f4cc-25f6-4c4c-94f7-4a4eb32215f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9576a74b-ddb4-49d0-883d-14767543ee33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IncludeInSearchResult&quot;)</value>
      <webElementGuid>1d771999-b6fb-42f6-aeee-7fdc4d2a0e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IncludeInSearchResult']</value>
      <webElementGuid>ea1e8317-a461-48c0-840a-b36030c6af64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-secondary-config-container']/div/div[3]/input</value>
      <webElementGuid>667b99ad-5c7b-4c6b-b5c5-77568d247362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/input</value>
      <webElementGuid>e45f4dc7-7dc6-4000-8e85-fa0cabfe055d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IncludeInSearchResult' and @name = 'IncludeInSearchResult' and @type = 'checkbox']</value>
      <webElementGuid>529e39d4-1625-4d8e-8aba-e0e897869ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
