<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Incluir en bsquedas_IsVisibleInTables</name>
   <tag></tag>
   <elementGuidId>6ab815a3-2a53-4c3e-b65e-6aa09128be9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsVisibleInTables</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsVisibleInTables']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0fb4e42-5c26-409b-9d2a-d444a36c963d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-1 ms-0 check-box</value>
      <webElementGuid>2ac95d8e-1076-47b2-980a-1412407a2360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09e3f9d0-0d3a-486a-8c1f-133accd5439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsVisibleInTables field is required.</value>
      <webElementGuid>66c62299-86c5-4827-819c-01bc2bcc92ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsVisibleInTables</value>
      <webElementGuid>ed63a7d3-0659-429e-80d5-60e803750f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsVisibleInTables</value>
      <webElementGuid>c1ce5ae6-d2d3-490b-a68d-dfaffe13fbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5eae92ed-8e87-42b9-88a5-a54a149cf1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09175547-60f4-4687-89c8-67a23a4d7dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsVisibleInTables&quot;)</value>
      <webElementGuid>499745c0-ea2c-4bba-872b-ca358edca515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsVisibleInTables']</value>
      <webElementGuid>a080345f-321f-490a-8abe-caaab3f94e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-secondary-config-container']/div/div[4]/div/input</value>
      <webElementGuid>af9cd873-489a-49f5-bd0e-aad9c960a258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b0cf3460-3d28-4467-854e-9ff79844580a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsVisibleInTables' and @name = 'IsVisibleInTables' and @type = 'checkbox']</value>
      <webElementGuid>4a1a2542-681a-4b94-9377-d36f3fb1e082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
