<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Autocrear_IsEditableUser</name>
   <tag></tag>
   <elementGuidId>305e1646-8a97-47a3-b93f-46f91f48f1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsEditableUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsEditableUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60de68f8-fc24-4ceb-9c12-221803cf0c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-1 ms-0 check-box</value>
      <webElementGuid>2a695805-1861-4182-8a05-4c87b61d6b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aeff7fac-8a34-4040-8152-60cc83a490a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsEditableUser field is required.</value>
      <webElementGuid>d5fb4eed-0dfd-4936-9d61-a6f3818bb89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsEditableUser</value>
      <webElementGuid>da6501d4-462e-4b29-ad3e-412faef1f3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsEditableUser</value>
      <webElementGuid>9cf53d64-7c59-4593-8cab-62cbb2f3550b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f4eb52ce-5f6b-40ef-914d-28c859bcac6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ee428a5-1518-496e-8523-65dbd91f0d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsEditableUser&quot;)</value>
      <webElementGuid>e230087b-33b6-4835-ae27-9fcd121c9111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsEditableUser']</value>
      <webElementGuid>ec0c60b0-de48-4916-bdd0-90a95798685b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-secondary-config-container']/div/div[2]/input</value>
      <webElementGuid>48f50f3b-aedf-4fcf-b5f9-046c763701b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/input</value>
      <webElementGuid>ad136fc7-1a4c-45f8-81f7-55353e2e5ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsEditableUser' and @name = 'IsEditableUser' and @type = 'checkbox']</value>
      <webElementGuid>e5895bf1-0763-4e9d-bbf0-d53ab9f1f3ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
