<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong</name>
   <tag></tag>
   <elementGuidId>0f0f1f50-248a-4302-83cd-87259389d766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#butFieldRowEditSubmit > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butFieldRowEditSubmit']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>246479fb-ab97-43ff-bcd2-25f9f32e6e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>c49f9171-2e65-4f98-89f2-90e386b60fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;butFieldRowEditSubmit&quot;)/strong[1]</value>
      <webElementGuid>3d47db24-3589-43a6-87ae-53b95a625fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='butFieldRowEditSubmit']/strong</value>
      <webElementGuid>2eef76f7-ab8c-4d95-bcc4-17c277de5116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::strong[1]</value>
      <webElementGuid>36ac7f12-9a04-4c71-bc52-f51671fc83b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Agregar validación'])[1]/following::strong[1]</value>
      <webElementGuid>d0a7b9fe-35b2-4888-a96c-f1b2746b492f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar eliminación'])[1]/preceding::strong[1]</value>
      <webElementGuid>aefb8a7c-a592-4934-a3de-233470057270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/preceding::strong[2]</value>
      <webElementGuid>94316d35-79e5-41f4-a7cf-cbc223b2d57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar']/parent::*</value>
      <webElementGuid>9287f646-502b-4690-ae3f-85ac990db185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/strong</value>
      <webElementGuid>b49ea623-7c46-47c1-a927-15a614312983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Guardar' or . = 'Guardar')]</value>
      <webElementGuid>1bff0d3c-e3e7-4593-95bf-231a089b4bbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
