<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ALB_deleteCurrencyBtn</name>
   <tag></tag>
   <elementGuidId>152c618a-4f23-4be3-8985-9bbf748d1668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deleteCurrencyBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='deleteCurrencyBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66e0da56-b36d-49c1-8799-e539d8921d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e8d04e81-6a85-46a4-8785-8ed28f2cc31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link text-primary</value>
      <webElementGuid>1e1e016b-a35e-40d1-91e5-9ec22895d369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteCurrencyBtn</value>
      <webElementGuid>91e51920-af89-4337-be28-a688932d1af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-companycurrencyid</name>
      <type>Main</type>
      <value>4f184be7-d8d6-4942-987d-046d3fb1a1bd</value>
      <webElementGuid>cc0a7a38-e394-410e-b898-6a84e2d52036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Eliminar
                        </value>
      <webElementGuid>e4cbe51c-be7f-4df7-8fe4-8c3f608f515f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteCurrencyBtn&quot;)</value>
      <webElementGuid>bd49330e-1b14-4f95-93c5-6e9eac961d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='deleteCurrencyBtn']</value>
      <webElementGuid>67ff6179-5abb-42ad-a677-843189641612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency-edit-modal']/div/div/form/div[2]/div/a</value>
      <webElementGuid>8f8085cd-ff04-4c56-9f4f-c0ea476e8940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALB'])[2]/following::a[1]</value>
      <webElementGuid>072b78ff-2d36-4f02-af23-2d8ed2fbe714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::a[1]</value>
      <webElementGuid>dbed66ac-6ee7-4e06-81e0-70516bb6b0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>cd98979f-ee5e-44af-a605-f221d1c76848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>e035c3ee-beb9-4828-bf24-e9ec89d206bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'deleteCurrencyBtn' and (text() = '
                             Eliminar
                        ' or . = '
                             Eliminar
                        ')]</value>
      <webElementGuid>3701f90f-1adf-41b9-8dd3-54eee936b254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
