<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automatico_newCurrency</name>
   <tag></tag>
   <elementGuidId>fb87eca3-a828-41c2-92d9-330b3ee46f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newCurrency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='newCurrency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b45b5956-3a33-4d2b-8d0d-df19ec83e5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newCurrency</value>
      <webElementGuid>ca175c6a-9a2c-48d4-b555-e5f17cfa5445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>0f7781e7-0681-40f6-9f00-af5060f1d98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-underline ms-2</value>
      <webElementGuid>cc2ec49d-fc97-4722-8e18-8ba161db4ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva moneda</value>
      <webElementGuid>cefb6ccd-8ecf-4cbc-8c91-270f485209a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newCurrency&quot;)</value>
      <webElementGuid>1f9da677-f188-4366-82f9-1c84d34d07b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='newCurrency']</value>
      <webElementGuid>bb5ea091-bd57-4767-8014-eb163dc2c5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-layout-container']/div/div/div/div[2]/a</value>
      <webElementGuid>cd5e81ea-e38b-4824-8d1b-600f6914f829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nueva moneda')]</value>
      <webElementGuid>dd0985f3-d893-496d-9910-4671fd5df1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automatico'])[4]/following::a[3]</value>
      <webElementGuid>6633e6f0-70c9-4af3-9e5e-32bc8fbd5066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UF'])[2]/following::a[3]</value>
      <webElementGuid>e7d68a0d-cd37-430d-940e-3e21a2e81098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar eliminación'])[1]/preceding::a[1]</value>
      <webElementGuid>4d977a06-0151-4e6d-8d74-1ee8d66ef475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::a[1]</value>
      <webElementGuid>830efc7d-f12c-4978-80ce-312991e69d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva moneda']/parent::*</value>
      <webElementGuid>5fe54a05-4fa2-450c-8d6d-55d41b19c93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>fe9137fc-0e3e-4370-9ab2-7713cb72ae71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[2]/a</value>
      <webElementGuid>f73014ec-06d0-4d62-8ba9-31f23b943cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'newCurrency' and @href = 'javascript:void(0);' and (text() = 'Nueva moneda' or . = 'Nueva moneda')]</value>
      <webElementGuid>cdac20e2-5d39-4432-9c36-df38e95696d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
