<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Campos_text-decoration-none</name>
   <tag></tag>
   <elementGuidId>37f515ea-baf2-44d1-8b0f-166c22cb5216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.text-decoration-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-layout-container']/div/div/div/div/nav/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88b8e511-b1db-44c7-98d2-1a80af8ff60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-decoration-none</value>
      <webElementGuid>178020b0-3f6a-4af1-83ca-ff998e05a92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/es/Currency/List</value>
      <webElementGuid>b582150a-57e7-4d3a-a960-cdcd4c948e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monedas</value>
      <webElementGuid>83f4916a-7729-4024-aca2-f5a0db52b77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout-container&quot;)/div[@class=&quot;main-panel&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 nav-sidebar&quot;]/nav[1]/ul[@class=&quot;list-unstyled&quot;]/li[3]/a[@class=&quot;text-decoration-none&quot;]</value>
      <webElementGuid>c336cd33-0ed6-4d9c-a1bf-5a9a3225f925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-layout-container']/div/div/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>ef33d92c-931b-4312-b2c1-1914a83ad1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Monedas')]</value>
      <webElementGuid>7f194928-beb6-4a2f-83fe-8290c25530fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campos'])[1]/following::a[1]</value>
      <webElementGuid>bfba726e-90bd-4b4f-a5f1-8376a144d745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empresa'])[1]/following::a[2]</value>
      <webElementGuid>f460b8ad-f5ee-424b-9e7c-eb39e808dc82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plantillas'])[1]/preceding::a[1]</value>
      <webElementGuid>3c23a95c-aa0b-46f8-9954-0861dcf1bd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extensiones'])[1]/preceding::a[2]</value>
      <webElementGuid>3abb71cb-0f73-4005-a9cf-7b06649bbd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monedas']/parent::*</value>
      <webElementGuid>973b7dde-0516-4aad-b155-4dc49804c196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/es/Currency/List')]</value>
      <webElementGuid>b8798338-dc12-4960-a738-0f3478960123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/nav/ul/li[3]/a</value>
      <webElementGuid>89a3e884-9b23-44ff-b538-6138653bd7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/es/Currency/List' and (text() = 'Monedas' or . = 'Monedas')]</value>
      <webElementGuid>2db88f7b-21fe-4eec-9c30-5a340f260a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
