<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo de importacin_ImportCode</name>
   <tag></tag>
   <elementGuidId>18a330bd-13be-4733-adab-3ca843615e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ImportCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ImportCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>204380ef-4626-4be1-a029-734381054763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>ab893438-1fb0-4ff9-ab48-313dfaec1173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>198db287-f3df-40f7-9068-22bf61d548c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Código de importación must be a string with a maximum length of 5.</value>
      <webElementGuid>ae6fc36e-e67f-42a8-a0da-c0de31e4bf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f1b85ef7-b632-4ca6-977e-d5d3c1dfa4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ImportCode</value>
      <webElementGuid>3894dc69-a935-4b7c-b409-2b0f67726e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>404f6fb1-97a4-4a5f-8436-d0fedddadd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ImportCode</value>
      <webElementGuid>0425aeac-dd8c-4c0a-bf3c-34b78ee8fd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11cae5b5-8934-40ae-a5c6-56215641bb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ImportCode&quot;)</value>
      <webElementGuid>f4ba152b-c2a5-4cf9-a9f1-98af1f2d3ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ImportCode']</value>
      <webElementGuid>4d87010c-310f-4622-a563-b2eda4f56cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency-edit-modal']/div/div/form/div/div[5]/div/input</value>
      <webElementGuid>785f9c5e-78e1-4b87-8b4f-b32d78f9ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>20cc3ea3-3522-4338-a0de-923054bf7125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ImportCode' and @name = 'ImportCode' and @type = 'text']</value>
      <webElementGuid>8f36552d-8734-4763-a545-0542eff2f5a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
