<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Smbolo_Symbol</name>
   <tag></tag>
   <elementGuidId>0204aaa4-42b1-4641-9fe7-e322c389a6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Symbol</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Symbol']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27462ca9-138a-4e59-a8b5-8f70a49d4e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>21fca588-2a79-4be3-8b8d-46fbd2334c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9971a7b3-a963-44ca-8893-d2297f44a3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Símbolo must be a string with a maximum length of 3.</value>
      <webElementGuid>f6a8eef6-269a-4c56-a218-b557df21d550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9f3e27ea-0ff9-4067-ba54-fe9d683ce607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Símbolo field is required.</value>
      <webElementGuid>99bf1e17-8583-46e3-9a04-160bb1069715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Symbol</value>
      <webElementGuid>5ad49e21-3592-4810-b54c-c9c94014de1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b5d5987e-7bc2-4d88-9edf-1fcc0fc23eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Symbol</value>
      <webElementGuid>bb1b4dc1-c733-4cc5-ad03-514d64f54484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2307edae-19bd-4090-b4df-3b28639bf8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Symbol&quot;)</value>
      <webElementGuid>42b6b937-52e8-42f0-94e6-4c7f32a45709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Symbol']</value>
      <webElementGuid>739ec77f-4152-4409-89f1-de8f69a2387d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency-edit-modal']/div/div/form/div/div[4]/div/input</value>
      <webElementGuid>9ca06647-2fb4-4835-a82b-03e2e0c8fd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>31fd6574-3e70-421a-89a0-4337159430c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Symbol' and @name = 'Symbol' and @type = 'text']</value>
      <webElementGuid>d145666b-8920-482a-885b-9b9addf0a8ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
