<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo de exportacin_ExportCode</name>
   <tag></tag>
   <elementGuidId>ed2737b4-5dea-4c50-b4c4-5e4339a173e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExportCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExportCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a104fe1-8338-4896-8a5b-fcc9efaf413b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>4038eb05-06ec-49a4-8133-f0b05f17a0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69f04735-b42f-4d2e-94df-4a1ea6fd88cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Código de exportación must be a string with a maximum length of 5.</value>
      <webElementGuid>c45fde84-4ca4-45ed-a15f-ae05856b86a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>06cac838-9347-403b-90b3-22ade63f7ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExportCode</value>
      <webElementGuid>9deb847e-d17a-4841-a772-20a5ab344a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8a00cf0d-41b1-499d-a2e1-da6ed1653306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExportCode</value>
      <webElementGuid>f975e2ec-a044-4e41-8e48-5e15db2db4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5e323ad-ce16-498b-86d5-abe48bd0c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExportCode&quot;)</value>
      <webElementGuid>ded8ec7d-b102-470f-abdc-1e8e42838cf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExportCode']</value>
      <webElementGuid>ef485470-ee37-4d37-8470-ffcb5e1e4fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency-edit-modal']/div/div/form/div/div[6]/div/input</value>
      <webElementGuid>682fe901-e311-4fcd-8453-6b3cd9bcf15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>8c95a291-23fc-4899-ab4f-80f06fad9427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ExportCode' and @name = 'ExportCode' and @type = 'text']</value>
      <webElementGuid>d00c4a06-4892-4991-99fe-f85edf431cb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
